# Generated by Django 3.2.5 on 2021-07-23 19:06

import dangidongi.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('when', models.DateTimeField()),
                ('description', models.TextField()),
                ('total_cost', models.FloatField(validators=[django.core.validators.RegexValidator(message='Total cost must be positive', regex='\\d+([.]\\d*)?')])),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('events', models.ManyToManyField(related_name='groups', to='dangidongi.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latt', models.FloatField()),
                ('lang', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=200, upload_to=dangidongi.models.Profile.name_it)),
                ('card_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid card number', regex='^(\\d{16})|(\\d{20})$')])),
                ('events', models.ManyToManyField(related_name='people', to='dangidongi.Event')),
                ('groups', models.ManyToManyField(related_name='people', to='dangidongi.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.RegexValidator(message='Payment amount must be positive', regex='\\d+([.]\\d*)?')])),
                ('is_initial_payment', models.BooleanField()),
                ('has_payed', models.BooleanField()),
                ('pay_proof_image', models.ImageField(max_length=200, upload_to='')),
                ('pay_proof_text', models.TextField()),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee_payments', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dangidongi.payment'),
        ),
        migrations.AddField(
            model_name='event',
            name='where',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='dangidongi.location'),
        ),
    ]
